[package]
name = "sbd_station_db_import"
version = "0.1.0"
authors = ["Willi Kappler <grandor@gmx.de>"]

[dependencies]
time = "0.1"
log = "0.3"
simplelog = "0.4"
clap = "2.26"
error-chain = "0.11"
regex = "0.2"
chrono = "0.4"
# half = "0.1.0"
byteorder = "1.1"
mysql = "12.0"
nom = "3.2"
